# Generated by Django 5.2 on 2025-06-18 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregada', 'Entregada'), ('evaluada', 'Evaluada')], max_length=20)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('imagen', 'Imagen'), ('video', 'Video'), ('documento', 'Documento'), ('otro', 'Otro')], max_length=20)),
                ('url', models.CharField(max_length=500)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.entregatarea')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('archivo', 'Archivo'), ('texto', 'Texto'), ('quiz', 'Quiz')], max_length=20)),
                ('fecha_entrega', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('calificacion_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.leccion')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('imagen', 'Imagen'), ('enlace', 'Enlace'), ('otro', 'Otro')], max_length=20)),
                ('url', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tarea')),
            ],
        ),
        migrations.AddField(
            model_name='entregatarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tarea'),
        ),
        migrations.CreateModel(
            name='TextoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.entregatarea')),
            ],
        ),
    ]
