# Generated by Django 5.2 on 2025-05-28 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('orden', models.IntegerField()),
                ('recurso_url', models.CharField(max_length=500)),
                ('fecha_disponible', models.DateField()),
                ('grupo_leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.grupoleccion')),
            ],
        ),
        migrations.CreateModel(
            name='LeccionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('sin ver', 'Sin ver'), ('avanzado', 'Avanzado'), ('finalizado', 'Finalizado')], max_length=20)),
                ('porcentaje_avance', models.IntegerField()),
                ('fecha_ultimo_avance', models.DateTimeField()),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.leccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.account')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('imagen', 'Imagen'), ('pdf', 'PDF'), ('audio', 'Audio'), ('enlace', 'Enlace'), ('otro', 'Otro')], max_length=20)),
                ('url', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.leccion')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoRecursoLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('visto', 'Visto')], max_length=20)),
                ('fecha_visto', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.account')),
                ('recurso_leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.recursoleccion')),
            ],
        ),
    ]
