# Generated by Django 5.2 on 2025-06-19 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('lessons', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.curso'),
            preserve_default=False,
        ),
    ]
