# Generated by Django 5.2 on 2025-05-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('clave', models.CharField(max_length=50)),
                ('nivel_educativo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('colonia', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('director', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
